
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2611
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080


jwt.secret=VGhpcy1pcy1hLXNlY3JldC1rZXktd2l0aC0zMi1ieXRlcy0xMjM0NTY3ODkw
jwt.expiration-ms=86400000

